#ifndef STATUS_HPP
#define STATUS_HPP

typedef enum {
  JUPITER_OK = 0,
  JUPITER_UNKNOWN,
  JUPITER_INVALID_ARGS,
  JUPITER_RESOURCE_EXHAUSTED,
  JUPITER_UNREACHABLE,
  JUPITER_TIMEOUT,
  JUPITER_EMPTY,
  JUPITER_OUT_OF_RANGE,
  JUPITER_UNIMPLEMENTED,
  JUPITER_UNINITIALIZED,
  JUPITER_INTERNAL_ERROR,
  JUPITER_INCOMPLETE,
  JUPITER_NUM_STATUS_CODES,
} JupiterStatus;

#endif