#include "bldc_control.h"

#include <stdio.h>

int main(void) {
    // TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE
    // TEST FAILURE TEST FAILURE TEST FAILURE TEST FAILURE
    return 0;
}